// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xzstkvoymfwumoopspev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6c3Rrdm95bWZ3dW1vb3BzcGV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjAxODAsImV4cCI6MjA2MjQzNjE4MH0.apBqnEQR7HMiOFYh2p-ODiUU-OHR2GUY40doHXwm8qw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);